import type { Course, Faculty, PastTimetable } from './types';

export const mockCourses: Course[] = [
  {
    id: 'cs101',
    code: 'CS 101',
    title: 'Introduction to Programming',
    credits: 4,
    department: 'Computer Science',
    description: 'Learn the fundamentals of programming using Python. Covers variables, control flow, functions, and basic data structures.',
    facultyId: 'fac001',
  },
  {
    id: 'cs202',
    code: 'CS 202',
    title: 'Data Structures & Algorithms',
    credits: 4,
    department: 'Computer Science',
    description: 'A deep dive into common data structures like trees, graphs, and hash tables, along with fundamental algorithms.',
    facultyId: 'fac001',
  },
  {
    id: 'cs303',
    code: 'CS 303',
    title: 'Operating Systems',
    credits: 3,
    department: 'Computer Science',
    description: 'Understand the core concepts of operating systems, including processes, threads, memory management, and file systems.',
    facultyId: 'fac002',
  },
  {
    id: 'math150',
    code: 'MATH 150',
    title: 'Calculus I',
    credits: 5,
    department: 'Mathematics',
    description: 'An introduction to differential calculus. Topics include limits, derivatives, and their applications.',
    facultyId: 'fac003',
  },
  {
    id: 'math250',
    code: 'MATH 250',
    title: 'Linear Algebra',
    credits: 4,
    department: 'Mathematics',
    description: 'Explore vector spaces, matrices, determinants, eigenvalues, and their applications in science and engineering.',
    facultyId: 'fac004',
  },
  {
    id: 'phy100',
    code: 'PHY 100',
    title: 'Classical Mechanics',
    credits: 4,
    department: 'Physics',
    description: 'Study the motion of objects using Newtonian mechanics. Covers kinematics, dynamics, energy, and momentum.',
    facultyId: 'fac003',
  },
  {
    id: 'phy210',
    code: 'PHY 210',
    title: 'Electromagnetism',
    credits: 4,
    department: 'Physics',
    description: 'An introduction to electric and magnetic fields, Maxwell\'s equations, and electromagnetic waves.',
    facultyId: 'fac005',
  },
  {
    id: 'hum120',
    code: 'HUM 120',
    title: 'World History: Ancient Civilizations',
    credits: 3,
    department: 'Humanities',
    description: 'A survey of major world civilizations from prehistory to the medieval period.',
    facultyId: 'fac006',
  },
  {
    id: 'hum300',
    code: 'HUM 300',
    title: 'Ethics in the Modern World',
    credits: 3,
    department: 'Humanities',
    description: 'Examines contemporary ethical dilemmas through the lens of major philosophical theories.',
    facultyId: 'fac006',
  },
   {
    id: 'cs404',
    code: 'CS 404',
    title: 'Computer Networks',
    credits: 3,
    department: 'Computer Science',
    description: 'An in-depth look at network protocols, architecture, and applications. OSI and TCP/IP models.',
    facultyId: 'fac002',
  },
  {
    id: 'math320',
    code: 'MATH 320',
    title: 'Probability Theory',
    credits: 3,
    department: 'Mathematics',
    description: 'Foundations of probability, random variables, distributions, and stochastic processes.',
    facultyId: 'fac004',
  },
  {
    id: 'phy350',
    code: 'PHY 350',
    title: 'Quantum Mechanics I',
    credits: 4,
    department: 'Physics',
    description: 'Introduction to the principles of quantum mechanics, including wave-particle duality and the Schrödinger equation.',
    facultyId: 'fac005',
  },
];

export const mockFaculty: Faculty[] = [
  {
    id: 'fac001',
    name: 'Dr. Alan Turing',
    email: 'alan.t@university.edu',
    department: 'Computer Science',
    subjects: ['CS 101', 'CS 202'],
  },
  {
    id: 'fac002',
    name: 'Dr. Grace Hopper',
    email: 'grace.h@university.edu',
    department: 'Computer Science',
    subjects: ['CS 303', 'CS 404'],
  },
  {
    id: 'fac003',
    name: 'Dr. Isaac Newton',
    email: 'isaac.n@university.edu',
    department: 'Mathematics',
    subjects: ['MATH 150', 'PHY 100'],
  },
  {
    id: 'fac004',
    name: 'Dr. Emmy Noether',
    email: 'emmy.n@university.edu',
    department: 'Mathematics',
    subjects: ['MATH 250', 'MATH 320'],
  },
  {
    id: 'fac005',
    name: 'Dr. Marie Curie',
    email: 'marie.c@university.edu',
    department: 'Physics',
    subjects: ['PHY 210', 'PHY 350'],
  },
  {
    id: 'fac006',
    name: 'Dr. Will Durant',
    email: 'will.d@university.edu',
    department: 'Humanities',
    subjects: ['HUM 120', 'HUM 300'],
  },
];

export const mockPastTimetables: PastTimetable[] = [
  {
    semester: 'Spring 2024',
    courses: [
      { code: 'CS 303', title: 'Operating Systems', credits: 3, grade: 'A' },
      { code: 'MATH 250', title: 'Linear Algebra', credits: 4, grade: 'A-' },
      { code: 'PHY 210', title: 'Electromagnetism', credits: 4, grade: 'B+' },
      { code: 'HUM 300', title: 'Ethics in the Modern World', credits: 3, grade: 'A' },
    ],
  },
  {
    semester: 'Fall 2023',
    courses: [
      { code: 'CS 202', title: 'Data Structures & Algorithms', credits: 4, grade: 'B+' },
      { code: 'MATH 150', title: 'Calculus I', credits: 5, grade: 'A' },
      { code: 'PHY 100', title: 'Classical Mechanics', credits: 4, grade: 'B' },
      { code: 'HUM 120', title: 'World History: Ancient Civilizations', credits: 3, grade: 'A-' },
    ],
  },
];
